apiVersion: v1
kind: Service
metadata:
  name: {{ include "console.fullname" . }}
  labels:
    {{- include "console.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: console
      protocol: TCP
      name: console
  selector:
    {{- include "console.selectorLabels" . | nindent 4 }}
