apiVersion: v1
kind: Service
metadata:
  name: console-np
  namespace: @@NAME_NS@@
spec:
  externalTrafficPolicy: Local
  type: NodePort
  ports:
  - name: "https"
    port: 443
    targetPort: 6443
    nodePort: @@NODE_PORT@@
  selector:
    app: console   
    hypercloud: ui