apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  namespace: @@NAME_NS@@
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: console
      hypercloud: ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: console
        hypercloud: ui
      name: hypercloud-ui
    spec:
      containers:
      - command:
        - /manager
        args:
        - --pwd=/var/tmp/configs/
        image: tmaxcloudck/console-operator:5.1.0.1
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts: 
        - mountPath: /var/tmp/configs
          name: dynamic-config        
      - command:  
        - /opt/bridge/bin/bridge
        - --public-dir=/opt/bridge/static
        - --listen=https://0.0.0.0:6443
        - --base-address=https://0.0.0.0:6443
        - --tls-cert-file=/var/https-cert/cert
        - --tls-key-file=/var/https-cert/key
        - --keycloak-realm=tmax
        - --keycloak-auth-url=https://testauth.tmaxcloud.com/auth
        - --keycloak-client-id=hypercloud4
        - --grafana-endpoint=http://grafana.monitoring.svc:3000/api/grafana/
        - --kiali-endpoint=https://kiali.istio-system.220.90.208.239.nip.io/api/kiali/
        - --mc-mode=true
        - --user-auth=hypercloud
        - --k8s-auth=hypercloud
        - --release-mode=true
        image: tmaxcloudck/hypercloud-console:0.5.1.13
        imagePullPolicy: IfNotPresent
        name: console
        ports:
        - containerPort: 6443
          protocol: TCP
        resources:
          limits:
            cpu: 400m
            memory: 500Mi
          requests:
            cpu: 400m
            memory: 500Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/https-cert
          name: https-cert
          readOnly: true
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
        - mountPath: /etc/timezone
          name: timezone
          readOnly: true
        - mountPath: /opt/bridge/configs
          name: dynamic-config 
      serviceAccount: @@NAME_NS@@-admin
      volumes:
      - name: https-cert
        secret:
          defaultMode: 288
          secretName: console-https-secret
      - hostPath:
          path: /etc/localtime
          type: ""
        name: localtime
      - hostPath:
          path: /etc/timezone
          type: ""
        name: timezone
      - emptyDir:
          medium: "Memory"
        name: dynamic-config