apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: traefik
data:
  traefik.yml: |
    http:
      routers:
        dashboard: 
          rule: PathPrefix(`/`)
          service: api@internal
          tls: {}
          entryPoints: 
          - traefik 
        k8s-router:
          rule: PathPrefix(`/`)
          entryPoints:
          - k8s
          service: k8s-service
          tls: {}
      services:
        k8s-service:
          loadBalancer:
            serversTransport: tls
            servers:
            - url: "https://192.168.9.155:6443"
      serversTransports:
        tls:
          insecureSkipVerify: true