apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: traefik
data:
  traefik.yml: |
    http:
      routers:
        k8s-router:
          rule: PathPrefix(`/`)
          entryPoints:
          - k8s
          service: k8s-service
          tls: {}
        console-router:
          rule: PathPrefix(`/`)
          entryPoints:
          - websecure
          service: console-service
          tls: {}
      services:
        k8s-service:
          loadBalancer:
            serversTransport: tls
            servers:
            - url: "https://192.168.9.155:6443"
        console-service:
          loadBalancer:
            serversTransport: tls
            servers:
            - url: "https://192.168.9.143"
      serversTransports:
        tls:
          insecureSkipVerify: true

