apiVersion: console.tmax.io/v1
kind: ConsoleYAMLSample
metadata:
  name: example-for-sample
spec:
  description: An example Job for sample add
  targetResource:
    apiVersion: batch/v1
    kind: Job
  title: Example Sample
  yaml: |
    Sample YAML
